# A simple neural network making a prediction

### What is a neural network?

In [1]:
weight = 0.1
def neural_network(input, weight):
    prediction = input * weight
    return prediction

number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(round(pred, 5))

# Making a prediction with multiple inputs

### Complete runnable code

In [2]:
def w_sum(inputs, weights):
    assert(len(inputs) == len(weights))
    
    output = 0
    
    for i in range(len(inputs)):
        output += (inputs[i] * weights[i])
        
    return output

def neural_network(inputs, weights):
    pred = w_sum(inputs, weights)
    return pred

weights = [0.1, 0.2, 0]
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

inputs = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(inputs, weights)

print(round(pred, 5))

0.98


### Challenge: Vector math

Write functions that perform the following operations:

- def elementwise_multiplication(vec_a, vec_b)
- def elementwise_addition(vec_a, vec_b)
- def vector_sum(vec_a)
- def vector_average(vec_a)

Then, see if you can use two of these methods to perform a dot product!

In [3]:
def elementwise_multiplication(vec_a, vec_b):
    assert(len(vec_a) == len(vec_b))
    return [vec_a[i] * vec_b[i] for i in range(len(vec_a))]

def elementwise_addition(vec_a, vec_b):
    assert(len(vec_a) == len(vec_b))
    return [vec_a[i] + vec_b[i] for i in range(len(vec_a))]

def vector_sum(vec_a):
    return sum(vec_a)

def vector_average(vec_a):
    return sum(vec_a) / len(vec_a)

print(elementwise_multiplication([1, 2, 3], [4, 5, 6]))
print(elementwise_addition([1, 2, 3], [4, 5, 6]))
print(vector_sum([1, 2, 3]))
print(vector_average([2, 2, 4, 4]))

def dot_product(vec_a, vec_b):
    assert(len(vec_a) == len(vec_b))
    product = sum(elementwise_multiplication(vec_a, vec_b))
    return round(product, 5)

print(dot_product([8.5, 0.65, 1.2], [0.1, 0.2, 0]))

[4, 10, 18]
[5, 7, 9]
6
3.0
0.98


# Multiple inputs

### Complete runnable code

In [4]:
import numpy as np

def neural_network(inputs, weights):
    pred = inputs.dot(weights)
    return pred

weights = np.array([0.1, 0.2, 0])

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

inputs = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(inputs, weights)

print(round(pred, 5))

0.98


# Making a prediction with multiple outputs

In [5]:
def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

def ele_mul(number, vector):
    output = [number * vector[i] for i in range(len(vector))]
    assert(len(output) == len(vector))
    return output

weights = [0.3, 0.2, 0.9]
wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]
pred = neural_network(input, weights)
print([round(ele, 5) for ele in pred])

[0.195, 0.13, 0.585]


# Predicting with multiple inputs and outputs
### Neural networks can predict multiple outputs given multiple inputs

In [9]:
def neural_network(inputs, weights):
    pred = vect_mat_mul(inputs, weights)
    return pred

def vect_mat_mul(vector, matrix):
    assert(len(vector) == len(matrix))
    output = [w_sum(vector, matrix[i]) for i in range(len(vector))]
    return output

def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

weights = [
    #toes, %win, #fans
    [0.1, 0.1, -0.3], # hurt?
    [0.1, 0.2, 0.0], # win?
    [0.0, 1.3, 0.1] # sad?
]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

inputs = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(inputs, weights)
print([round(ele, 5) for ele in pred])

[0.555, 0.98, 0.965]


# Predicting on predictions

### Neural networks can be stacked!

In [12]:
def neural_network(inputs, weights):
    hid = vect_mat_mul(inputs, weights[0])
    pred = vect_mat_mul(hid, weights[1])
    return pred

def vect_mat_mul(vector, matrix):
    assert(len(vector) == len(matrix))
    output = [w_sum(vector, matrix[i]) for i in range(len(vector))]
    return output

def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

ih_wgt = [
    #toes, %win, #fans
    [0.1, 0.2, -0.1], # hid[0]
    [-0.1, 0.1, 0.9], # hid[1]
    [0.1, 0.4, 0.1] # hid[2]
]

hp_wgt = [
#  hid[0],hid[1],hid[2]
    [0.3, 1.1, -0.3], # hurt?
    [0.1, 0.2, 0.0], # win?
    [0.0, 1.3, 0.1] # sad?
]

weights = [ih_wgt, hp_wgt]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

inputs = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(inputs, weights)
print([round(ele, 5) for ele in pred])

[0.2135, 0.145, 0.5065]


### NumPy version

In [14]:
import numpy as np

def neural_network(inputs, weights):
    hid = inputs.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

#toes, %win, #fans
ih_wgt = np.array([
    [0.1, 0.2, -0.1], # hid[0]
    [-0.1, 0.1, 0.9], # hid[1]
    [0.1, 0.4, 0.1] # hid[2]
]).T

# hid[0], hid[1], hid[2]
hp_wgt = np.array([
    [0.3, 1.1, -0.3], # hurt?
    [0.1, 0.2, 0.0], # win?
    [0.0, 1.3, 0.1] # sad?
]).T

weights = [ih_wgt, hp_wgt]

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

inputs = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(inputs, weights)
print([round(ele, 5) for ele in pred])

[0.2135, 0.145, 0.5065]


# A quick primer on NumPy

### NumPy does a few things for you. Let's reveal the magic.

In [23]:
import numpy as np

a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

d = np.zeros((2, 4))
e = np.random.rand(2, 5)

print(a)
print(b)
print(c)
print(d)
print(e)
print()

print(a * 0.1)
print(a + 1)
print(c * 0.2)
print(a * b)
print(a * b * 0.2)
print(a * c)
# print(a * e) ERROR

f = np.zeros((1, 4))
g = np.zeros((4, 3))
print()
print(f)
print(g)
h = f.dot(g)
print()
print(h)
print()
print(h.shape)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.97205069 0.79787714 0.29202472 0.21230972 0.79373077]
 [0.90315085 0.45487812 0.40377613 0.2381625  0.32987447]]

[0.  0.1 0.2 0.3]
[1 2 3 4]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]

[[0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]]

(1, 3)
